# Generated by Django 3.2.8 on 2025-08-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='github_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
