# Generated by Django 3.2.8 on 2025-08-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20250801_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gitee_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gitee_username',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
