# Generated by Django 3.2.8 on 2025-08-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_adminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='reply_read',
            field=models.BooleanField(default=False),
        ),
    ]
