# Generated by Django 3.2.8 on 2026-10-09 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20250817_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlorrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadout', models.CharField(blank=True, default='', max_length=255)),
                ('kills_total', models.PositiveIntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='florr_profile', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='FlorrPetal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='florr_petals', to='game.player')),
            ],
            options={
                'unique_together': {('player', 'kind')},
            },
        ),
    ]
