# Generated by Django 3.2.8 on 2026-10-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_florr_profile_and_petals'),
    ]

    operations = [
        migrations.AddField(
            model_name='florrpetal',
            name='rarity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='florrpetal',
            unique_together={('player', 'kind', 'rarity')},
        ),
    ]
